// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: glennsteven/config/v1/http.proto

package configpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpServer struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Host                       *string                `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Port                       *int32                 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	ReadTimeout                *durationpb.Duration   `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout" json:"read_timeout,omitempty"`
	WriteTimeout               *durationpb.Duration   `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout" json:"write_timeout,omitempty"`
	ShutdownGracePeriodTimeout *durationpb.Duration   `protobuf:"bytes,5,opt,name=shutdown_grace_period_timeout,json=shutdownGracePeriodTimeout" json:"shutdown_grace_period_timeout,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *HttpServer) Reset() {
	*x = HttpServer{}
	mi := &file_glennsteven_config_v1_http_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpServer) ProtoMessage() {}

func (x *HttpServer) ProtoReflect() protoreflect.Message {
	mi := &file_glennsteven_config_v1_http_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpServer.ProtoReflect.Descriptor instead.
func (*HttpServer) Descriptor() ([]byte, []int) {
	return file_glennsteven_config_v1_http_proto_rawDescGZIP(), []int{0}
}

func (x *HttpServer) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

func (x *HttpServer) GetPort() int32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *HttpServer) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *HttpServer) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *HttpServer) GetShutdownGracePeriodTimeout() *durationpb.Duration {
	if x != nil {
		return x.ShutdownGracePeriodTimeout
	}
	return nil
}

type HttpClient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *string                `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpClient) Reset() {
	*x = HttpClient{}
	mi := &file_glennsteven_config_v1_http_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpClient) ProtoMessage() {}

func (x *HttpClient) ProtoReflect() protoreflect.Message {
	mi := &file_glennsteven_config_v1_http_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpClient.ProtoReflect.Descriptor instead.
func (*HttpClient) Descriptor() ([]byte, []int) {
	return file_glennsteven_config_v1_http_proto_rawDescGZIP(), []int{1}
}

func (x *HttpClient) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

var File_glennsteven_config_v1_http_proto protoreflect.FileDescriptor

const file_glennsteven_config_v1_http_proto_rawDesc = "" +
	"\n" +
	" glennsteven/config/v1/http.proto\x12\x15glennsteven.config.v1\x1a\x1egoogle/protobuf/duration.proto\"\x90\x02\n" +
	"\n" +
	"HttpServer\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12<\n" +
	"\fread_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x12\\\n" +
	"\x1dshutdown_grace_period_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x1ashutdownGracePeriodTimeout\"&\n" +
	"\n" +
	"HttpClient\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddressB:Z8github.com/glennsteven/hub/go/configv1/configpb;configpbb\beditionsp\xe8\a"

var (
	file_glennsteven_config_v1_http_proto_rawDescOnce sync.Once
	file_glennsteven_config_v1_http_proto_rawDescData []byte
)

func file_glennsteven_config_v1_http_proto_rawDescGZIP() []byte {
	file_glennsteven_config_v1_http_proto_rawDescOnce.Do(func() {
		file_glennsteven_config_v1_http_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_glennsteven_config_v1_http_proto_rawDesc), len(file_glennsteven_config_v1_http_proto_rawDesc)))
	})
	return file_glennsteven_config_v1_http_proto_rawDescData
}

var file_glennsteven_config_v1_http_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_glennsteven_config_v1_http_proto_goTypes = []any{
	(*HttpServer)(nil),          // 0: glennsteven.config.v1.HttpServer
	(*HttpClient)(nil),          // 1: glennsteven.config.v1.HttpClient
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_glennsteven_config_v1_http_proto_depIdxs = []int32{
	2, // 0: glennsteven.config.v1.HttpServer.read_timeout:type_name -> google.protobuf.Duration
	2, // 1: glennsteven.config.v1.HttpServer.write_timeout:type_name -> google.protobuf.Duration
	2, // 2: glennsteven.config.v1.HttpServer.shutdown_grace_period_timeout:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_glennsteven_config_v1_http_proto_init() }
func file_glennsteven_config_v1_http_proto_init() {
	if File_glennsteven_config_v1_http_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_glennsteven_config_v1_http_proto_rawDesc), len(file_glennsteven_config_v1_http_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_glennsteven_config_v1_http_proto_goTypes,
		DependencyIndexes: file_glennsteven_config_v1_http_proto_depIdxs,
		MessageInfos:      file_glennsteven_config_v1_http_proto_msgTypes,
	}.Build()
	File_glennsteven_config_v1_http_proto = out.File
	file_glennsteven_config_v1_http_proto_goTypes = nil
	file_glennsteven_config_v1_http_proto_depIdxs = nil
}
