// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: glennsteven/featuregate/v1/featuregate.proto

package featuregatepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IsFeatureActiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Region        *string                `protobuf:"bytes,2,opt,name=region" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFeatureActiveRequest) Reset() {
	*x = IsFeatureActiveRequest{}
	mi := &file_glennsteven_featuregate_v1_featuregate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFeatureActiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFeatureActiveRequest) ProtoMessage() {}

func (x *IsFeatureActiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_glennsteven_featuregate_v1_featuregate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFeatureActiveRequest.ProtoReflect.Descriptor instead.
func (*IsFeatureActiveRequest) Descriptor() ([]byte, []int) {
	return file_glennsteven_featuregate_v1_featuregate_proto_rawDescGZIP(), []int{0}
}

func (x *IsFeatureActiveRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *IsFeatureActiveRequest) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

type IsFeatureActiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        *bool                  `protobuf:"varint,1,opt,name=active" json:"active,omitempty"`
	Reason        *string                `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsFeatureActiveResponse) Reset() {
	*x = IsFeatureActiveResponse{}
	mi := &file_glennsteven_featuregate_v1_featuregate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsFeatureActiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsFeatureActiveResponse) ProtoMessage() {}

func (x *IsFeatureActiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_glennsteven_featuregate_v1_featuregate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsFeatureActiveResponse.ProtoReflect.Descriptor instead.
func (*IsFeatureActiveResponse) Descriptor() ([]byte, []int) {
	return file_glennsteven_featuregate_v1_featuregate_proto_rawDescGZIP(), []int{1}
}

func (x *IsFeatureActiveResponse) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *IsFeatureActiveResponse) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

var File_glennsteven_featuregate_v1_featuregate_proto protoreflect.FileDescriptor

const file_glennsteven_featuregate_v1_featuregate_proto_rawDesc = "" +
	"\n" +
	",glennsteven/featuregate/v1/featuregate.proto\x12\x1aglennsteven.featuregate.v1\"D\n" +
	"\x16IsFeatureActiveRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\"I\n" +
	"\x17IsFeatureActiveResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\x90\x01\n" +
	"\x12FeatureGateService\x12z\n" +
	"\x0fIsFeatureActive\x122.glennsteven.featuregate.v1.IsFeatureActiveRequest\x1a3.glennsteven.featuregate.v1.IsFeatureActiveResponseB;Z9github.com/glennsteven/hub/go/featuregatev1/featuregatepbb\beditionsp\xe8\a"

var (
	file_glennsteven_featuregate_v1_featuregate_proto_rawDescOnce sync.Once
	file_glennsteven_featuregate_v1_featuregate_proto_rawDescData []byte
)

func file_glennsteven_featuregate_v1_featuregate_proto_rawDescGZIP() []byte {
	file_glennsteven_featuregate_v1_featuregate_proto_rawDescOnce.Do(func() {
		file_glennsteven_featuregate_v1_featuregate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_glennsteven_featuregate_v1_featuregate_proto_rawDesc), len(file_glennsteven_featuregate_v1_featuregate_proto_rawDesc)))
	})
	return file_glennsteven_featuregate_v1_featuregate_proto_rawDescData
}

var file_glennsteven_featuregate_v1_featuregate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_glennsteven_featuregate_v1_featuregate_proto_goTypes = []any{
	(*IsFeatureActiveRequest)(nil),  // 0: glennsteven.featuregate.v1.IsFeatureActiveRequest
	(*IsFeatureActiveResponse)(nil), // 1: glennsteven.featuregate.v1.IsFeatureActiveResponse
}
var file_glennsteven_featuregate_v1_featuregate_proto_depIdxs = []int32{
	0, // 0: glennsteven.featuregate.v1.FeatureGateService.IsFeatureActive:input_type -> glennsteven.featuregate.v1.IsFeatureActiveRequest
	1, // 1: glennsteven.featuregate.v1.FeatureGateService.IsFeatureActive:output_type -> glennsteven.featuregate.v1.IsFeatureActiveResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_glennsteven_featuregate_v1_featuregate_proto_init() }
func file_glennsteven_featuregate_v1_featuregate_proto_init() {
	if File_glennsteven_featuregate_v1_featuregate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_glennsteven_featuregate_v1_featuregate_proto_rawDesc), len(file_glennsteven_featuregate_v1_featuregate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_glennsteven_featuregate_v1_featuregate_proto_goTypes,
		DependencyIndexes: file_glennsteven_featuregate_v1_featuregate_proto_depIdxs,
		MessageInfos:      file_glennsteven_featuregate_v1_featuregate_proto_msgTypes,
	}.Build()
	File_glennsteven_featuregate_v1_featuregate_proto = out.File
	file_glennsteven_featuregate_v1_featuregate_proto_goTypes = nil
	file_glennsteven_featuregate_v1_featuregate_proto_depIdxs = nil
}
