// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: glennsteven/featuregate/v1/featuregate.proto

package featuregatepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FeatureGateService_IsFeatureActive_FullMethodName = "/glennsteven.featuregate.v1.FeatureGateService/IsFeatureActive"
	FeatureGateService_DisableFeature_FullMethodName  = "/glennsteven.featuregate.v1.FeatureGateService/DisableFeature"
)

// FeatureGateServiceClient is the client API for FeatureGateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeatureGateServiceClient interface {
	IsFeatureActive(ctx context.Context, in *IsFeatureActiveRequest, opts ...grpc.CallOption) (*IsFeatureActiveResponse, error)
	DisableFeature(ctx context.Context, in *DisableFeatureRequest, opts ...grpc.CallOption) (*DisableFeatureResponse, error)
}

type featureGateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeatureGateServiceClient(cc grpc.ClientConnInterface) FeatureGateServiceClient {
	return &featureGateServiceClient{cc}
}

func (c *featureGateServiceClient) IsFeatureActive(ctx context.Context, in *IsFeatureActiveRequest, opts ...grpc.CallOption) (*IsFeatureActiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsFeatureActiveResponse)
	err := c.cc.Invoke(ctx, FeatureGateService_IsFeatureActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *featureGateServiceClient) DisableFeature(ctx context.Context, in *DisableFeatureRequest, opts ...grpc.CallOption) (*DisableFeatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableFeatureResponse)
	err := c.cc.Invoke(ctx, FeatureGateService_DisableFeature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeatureGateServiceServer is the server API for FeatureGateService service.
// All implementations should embed UnimplementedFeatureGateServiceServer
// for forward compatibility.
type FeatureGateServiceServer interface {
	IsFeatureActive(context.Context, *IsFeatureActiveRequest) (*IsFeatureActiveResponse, error)
	DisableFeature(context.Context, *DisableFeatureRequest) (*DisableFeatureResponse, error)
}

// UnimplementedFeatureGateServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeatureGateServiceServer struct{}

func (UnimplementedFeatureGateServiceServer) IsFeatureActive(context.Context, *IsFeatureActiveRequest) (*IsFeatureActiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsFeatureActive not implemented")
}
func (UnimplementedFeatureGateServiceServer) DisableFeature(context.Context, *DisableFeatureRequest) (*DisableFeatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableFeature not implemented")
}
func (UnimplementedFeatureGateServiceServer) testEmbeddedByValue() {}

// UnsafeFeatureGateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeatureGateServiceServer will
// result in compilation errors.
type UnsafeFeatureGateServiceServer interface {
	mustEmbedUnimplementedFeatureGateServiceServer()
}

func RegisterFeatureGateServiceServer(s grpc.ServiceRegistrar, srv FeatureGateServiceServer) {
	// If the following call panics, it indicates UnimplementedFeatureGateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeatureGateService_ServiceDesc, srv)
}

func _FeatureGateService_IsFeatureActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsFeatureActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureGateServiceServer).IsFeatureActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureGateService_IsFeatureActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureGateServiceServer).IsFeatureActive(ctx, req.(*IsFeatureActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeatureGateService_DisableFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableFeatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeatureGateServiceServer).DisableFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeatureGateService_DisableFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeatureGateServiceServer).DisableFeature(ctx, req.(*DisableFeatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FeatureGateService_ServiceDesc is the grpc.ServiceDesc for FeatureGateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeatureGateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "glennsteven.featuregate.v1.FeatureGateService",
	HandlerType: (*FeatureGateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsFeatureActive",
			Handler:    _FeatureGateService_IsFeatureActive_Handler,
		},
		{
			MethodName: "DisableFeature",
			Handler:    _FeatureGateService_DisableFeature_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "glennsteven/featuregate/v1/featuregate.proto",
}
